[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/upscale/"
  status = 301

[[redirects]]
  from = "/upscale/*"
  to = "/upscale/index.html"
  status = 200


[[redirects]]
from = "/pdf"
to = "https://https://lddpdf.netlify.app/"
status = 301
force = true

[[redirects]]
from = "/pdf/*"
to = "https://https://lddpdf.netlify.app/:splat"
status = 301
force = true
